# Generated by Django 3.2.8 on 2023-01-29 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carteiras', '0002_auto_20230128_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='acao',
        ),
    ]
