# Generated by Django 3.2.8 on 2022-12-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0002_rename_acoes_acoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor_atual', models.CharField(max_length=200)),
                ('quantidade_atual', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Acoe',
        ),
    ]
