# Generated by Django 3.2.8 on 2023-01-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0004_carteira_acoes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carteira_Acoes',
        ),
    ]
