# Generated by Django 3.2.8 on 2023-01-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0005_delete_carteira_acoes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acoes',
            old_name='quantidade_atual',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='acoes',
            old_name='sigla',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='acoes',
            old_name='valor_atual',
            new_name='moeda',
        ),
        migrations.AddField(
            model_name='acoes',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
