# Generated by Django 3.2.8 on 2023-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0006_auto_20230129_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='codigo',
            field=models.CharField(max_length=4000),
        ),
    ]
