# Generated by Django 3.2.8 on 2023-01-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0007_alter_acoes_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='codigo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='acoes',
            name='info',
            field=models.CharField(max_length=4000),
        ),
    ]
