# Generated by Django 3.2.8 on 2023-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0008_auto_20230129_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acoes',
            name='info',
            field=models.TextField(),
        ),
    ]
