# Generated by Django 3.2.8 on 2023-01-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira_acoes', '0002_alter_carteira_acoes_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira_acoes',
            name='quantidade_atual',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
