# Generated by Django 3.2.8 on 2023-02-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carteira_acoes', '0003_carteira_acoes_quantidade_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteira_acoes',
            name='dataCompra',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carteira_acoes',
            name='precoPago',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
